### ISSUE TITLE
IOError: error while writing to output stream

### ISSUE THREAD

**Issue by gpfransen** [inconvergent/sand-spline#1]
Hi,

First of all; awesome script, many thanks for sharing!

I am experiencing the following issue;

> Traceback (most recent call last):
>   File "/home/gp/render2d/render/render/render.py", line 380, in step_wrap
>     res = self.step(self)
>   File "/home/gp/render2d/sand-spline/modules/sand.py", line 95, in wrap
>     render.write_to_png(name)
>   File "/home/gp/render2d/render/render/render.py", line 56, in write_to_png
>     self.sur.write_to_png(fn)
> IOError: error while writing to output stream

I have played around quite a bit but don't find the mischief unfortunately :/ 

When I write the file directly from render.write_to_png('file.png') it succeeds and fn will show output in terminal.

Does anybody have a clue what is happening?

Thanks!

**Comment by inconvergent** [comment]
a folder named 'res' is missing in the main repo. i'll fix it shortly, but you can fix it by just creating that folder.

**Comment by gpfransen** [comment]
Many thanks, that resolved it :)
