### ISSUE TITLE
Sand object - TypeError: expected a writeable buffer object

### ISSUE THREAD

**Issue by mikecj184** [inconvergent/sand-spline#2]
Hi, 
Great script. Currently, I'm trying to get this code base working. I'm getting the following errors when i do so!
I'm trying this on a Mac OS X 10.11.6 using python 2.7. So far I've been able to install all the dependencies including fn and sand.

When i run: python main-bg.py
I get these errors...

> Traceback(most recent call last):
  File "main-bg.py", line 137, in <module>
    main()
  File "main-bg.py", line 114, in main
    sand = Sand(SIZE)
  File "src/sand.pyx", line 44, in sand.Sand.__init__ (./src/sand.c:2908)
  File "/Users/mikecj/Library/Python/2.7/lib/python/site-packages/cairocffi-0.7.2-py2.7.egg/cairocffi/surfaces.py", line 660, in create_for_data
    return cls(format, width, height, data, stride)
  File "/Users/mikecj/Library/Python/2.7/lib/python/site-packages/cairocffi-0.7.2-py2.7.egg/cairocffi/surfaces.py", line 646, in __init__
    address, length = from_buffer(data)
  File "/Users/mikecj/Library/Python/2.7/lib/python/site-packages/cairocffi-0.7.2-py2.7.egg/cairocffi/surfaces.py", line 68, in from_buffer
    return ctypes.addressof(ctypes.c_char.from_buffer(obj)), len(obj)
TypeError: expected a writeable buffer object

Thanks :)

**Comment by inconvergent** [comment]
i have only tested this with python 3. it looks like you may be using python 2.7 here.

**Comment by mikecj184** [comment]
Thanks for the quick revert.
I tried to run this in python3 but, couldn't. Python3 could not load fn module. There were no errors when I installed in python3.
Here are the outputs:

1. python3 main-bg.py
`Traceback (most recent call last):
  File "main-bg.py", line 136, in <module>
    main()
  File "main-bg.py", line 110, in main
    from fn import Fn
  File "/usr/local/lib/python3.5/site-packages/fn-0.0.6-py3.5.egg/fn/__init__.py", line 29, in <module>
ImportError: cannot import name 'Fn'`

2. inside fn-master repository: sudo ./setup.py install
`running install
running bdist_egg
running egg_info
writing fn.egg-info/PKG-INFO
writing top-level names to fn.egg-info/top_level.txt
writing requirements to fn.egg-info/requires.txt
writing entry points to fn.egg-info/entry_points.txt
writing dependency_links to fn.egg-info/dependency_links.txt
reading manifest file 'fn.egg-info/SOURCES.txt'
writing manifest file 'fn.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/fn
copying build/lib/fn/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/fn
copying build/lib/fn/fn.py -> build/bdist.macosx-10.11-x86_64/egg/fn
byte-compiling build/bdist.macosx-10.11-x86_64/egg/fn/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/fn/fn.py to fn.cpython-35.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/entry_points.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying fn.egg-info/zip-safe -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
creating 'dist/fn-0.0.6-py3.5.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing fn-0.0.6-py3.5.egg
Removing /usr/local/lib/python3.5/site-packages/fn-0.0.6-py3.5.egg
Copying fn-0.0.6-py3.5.egg to /usr/local/lib/python3.5/site-packages
fn 0.0.6 is already the active version in easy-install.pth
Installing fn script to /usr/local/bin

Installed /usr/local/lib/python3.5/site-packages/fn-0.0.6-py3.5.egg
Processing dependencies for fn==0.0.6
Searching for docopt==0.6.2
Best match: docopt 0.6.2
Processing docopt-0.6.2-py3.5.egg
docopt 0.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/site-packages/docopt-0.6.2-py3.5.egg
Finished processing dependencies for fn==0.0.6`/

**Comment by inconvergent** [comment]
I do belive fn is listed as a prerequisite.

**Comment by inconvergent** [comment]
i don't know. you have to make sure that fn is in the path of the same python that you are executing sand spline from. i am unable to recreate this, and i can't really see a way for me to do anything about it. however fn is only used to generate file names. you can circumvent it by modifying the main file in sand spline.

**Comment by inconvergent** [comment]
[i deleted my original post because i posted it from my phone and apparently i didn't see all of it. very sorry about that.]

**Comment by inconvergent** [comment]
i found a possible error on my part. the link to the fn library was the wrong one. i've updated it. and it was supposed to be: https://github.com/inconvergent/fn-python3

**Comment by inconvergent** [comment]
i'm in the middle of transitioning many repos to python 3, so i'm afraid there may be more mistakes like this on my part.

**Comment by mikecj184** [comment]
Hi! That's good news. Thanks a lot.
I tried it and could now import fn in python 3 - `from fn import Fn`

But, again when i run:
`python3 main-bg.py`

I get errors from fn python3. 

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/fn-0.1.0-py3.5.egg/fn/fn.py", line 68, in __init_repo
  File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 171, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/mikecj/Documents/TimeBlur/Python/Inconvergent/sand-spline/sand-spline
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main-bg.py", line 136, in <module>
    main()
  File "main-bg.py", line 117, in main
    fn = Fn(prefix='./res/', postfix='.png')
  File "/usr/local/lib/python3.5/site-packages/fn-0.1.0-py3.5.egg/fn/fn.py", line 32, in __init__
  File "/usr/local/lib/python3.5/site-packages/fn-0.1.0-py3.5.egg/fn/fn.py", line 73, in __init_repo
RuntimeError: fn: directory is not a git repository, or git is not installed.


Meanwhile, I will try removing the dependency on fn, and try run without it.

Thanks

**Comment by inconvergent** [comment]
Hi again. this last error is because FN (which is a tool i have fashioned solely for my own benefit) expects the folder from which it is run to be a git repo. i could improve upon this, but i don't have the time to do it at the moment. if you could please work around the FN requirement in sand spline, this should be sufficient for you to get things working.
