### ISSUE TITLE
Many scripts appear to rely on a group of "color files" not included in the repo

### ISSUE THREAD

**Issue by chrisuehlinger** [inconvergent/sand-spline#4]
Hey there! I was really taken with these visualizations and wanted to try and render a few on my own box. However, after I got everything installed, this error began showing up whenever I ran one of the main-* scripts:

```
Traceback (most recent call last):
  File "main-circle.py", line 96, in <module>
    main()
  File "main-circle.py", line 74, in main
    colors = get_colors('../colors/dark_cyan_white_black2.gif')
  File "/Users/Chris/Development/sand-spline/modules/helpers.py", line 40, in get_colors
    im = Image.open(f)
  File "/Users/Chris/Development/sand-spline/p3env/lib/python3.5/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../colors/dark_cyan_white_black2.gif'
```

Could you please move those files into the repo so that it can be self-contained?

Thanks!
-Chris

**Comment by inconvergent** [comment]
No I cannot. But you can use your own color files. Png, jpg or gif should work.

**Comment by inconvergent** [comment]
they are just images, just so there isn't any confusion.

**Comment by chrismelba** [comment]
What should the image files look like?

**Comment by inconvergent** [comment]
anything. it should have a nice set of colors that you like. you have to experiment. use a picture of water or a picture of a tree or a macro of a mushroom etc.
